#cloud-config
users:
  - name: workshop
    groups: [adm, docker]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - docker.io
  - curl
  - git
  - jq

runcmd:
  # Setup Docker Swarm
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker workshop
  - docker swarm init
  - docker network create -d overlay proxy
  
  # Install abra
  - curl -fsSL https://install.abra.coopcloud.tech | bash
  - mv /root/.local/bin/abra /usr/local/bin/
  - chmod +x /usr/local/bin/abra
  
  # Pre-configure abra server for this participant
  - sudo -u workshop mkdir -p /home/workshop/.abra/servers
  - sudo -u workshop abra server add ${participant_name}.${domain}
  
  # Pre-setup Traefik
  - sudo -u workshop abra app new traefik --domain=traefik.${participant_name}.${domain} --server=${participant_name}.${domain}
